create table "public"."posts" (
    "created_at" timestamp with time zone default now(),
    "updated_at" timestamp with time zone default now(),
    "topic_id" bigint,
    "author_name" character varying,
    "author_email" character varying,
    "body_md" text,
    "body_html" text,
    "original_id" bigint,
    "id" uuid not null default uuid_generate_v4(),
    "registered" character varying
);


alter table "public"."posts" enable row level security;

create table "public"."topics" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "updated_at" timestamp with time zone default now(),
    "name" text,
    "order_nr" bigint,
    "parent_id" bigint,
    "description_md" text,
    "description_html" text,
    "announcement_md" text,
    "announcement_html" text
);


alter table "public"."topics" enable row level security;

CREATE UNIQUE INDEX posts_pkey ON public.posts USING btree (id);

CREATE UNIQUE INDEX topics_pkey ON public.topics USING btree (id);

alter table "public"."posts" add constraint "posts_pkey" PRIMARY KEY using index "posts_pkey";

alter table "public"."topics" add constraint "topics_pkey" PRIMARY KEY using index "topics_pkey";

alter table "public"."posts" add constraint "posts_topic_id_fkey" FOREIGN KEY (topic_id) REFERENCES topics(id) not valid;

alter table "public"."posts" validate constraint "posts_topic_id_fkey";


